import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 10,
    fontSize: 12,
  },
  title: { fontSize: 18, textAlign: "center", marginBottom: 10 },
  section: { marginBottom: 10 },
  hotel: { fontSize: 14, fontWeight: "bold" },
  imageB: {
    width: "100%",
    height: "100%",
  },
  imageright: {
    width: "40vw",
    height: "100%",
    marginBottom: 10,
    objectFit: "cover",
  },
  boldText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#070705",
    marginBottom: 10,
    textDecoration: "underline",
  },
  vehicle: { marginLeft: 10, fontSize: 12 },
  flex: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  flexd: {
    display: "flex",
    flexDirection: "row",
    border: "1px solid #DFDFDF",
    borderRight: "none",
  },
  block: {
    width: "60px",
    height: "60px",
    backgroundColor: "#4497A3",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  details: {
    padding: 10,
    gap: 5,
  },
  dayContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  pagestyle: { fontSize: 18, color: "#070705", fontWeight: "bold", textDecoration: "underline", marginBottom: 10, marginTop: 10 },
  heading: { fontSize: 26, fontWeight: "bold", color: "#1f86a3", marginBottom: 10 },
  accommodationContainer: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    height: 189,
    justifyContent: "space-between",
    borderRadius: 5,
    border: "1px solid #4497A3",
    backgroundColor: "#F4F9FA",
    marginBottom: 8,
  },
  leftSection: { padding: 10, width: "50%" },
  row: { display: "flex", flexDirection: "row", alignItems: "center", gap: 6 },
  nightBox: {
    backgroundColor: "lightblue",
    borderRadius: 5,
    border: "1px solid #4497A3",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    display: "flex",
    width: 30,
    height: 30,
  },
  roomBox: {
    backgroundColor: "lightblue",
    padding: 10,
    borderRadius: 5,
    border: "1px solid #4497A3",
    alignItems: "center",
    justifyContent: "center",
    display: "flex",
    width: 50,
    height: 50,
  },
  textGray: { fontSize: 13, color: "gray" },
  textBlue: { fontSize: 10, color: "#4497A3" },
  rightSection: { width: "50%" },
  image: { width: "100%", height: "100%" },
  table: { display: "flex", flexDirection: "column", width: "100%" },
  trow: { display: "flex", flexDirection: "row" },
  cell: {
    width: "50%",
    border: "1px solid black",
    padding: 10,
    textAlign: "center",
  },
  tncheading: {
    fontSize: 18,
    fontWeight: "bold",
    textDecoration: "underline",
    marginBottom: 10,
  },
}); 